.zuul.d/jobs.yaml, .zuul.d/project.yaml, tests/with_container_images.yaml
These are the same jobs as before, just adding them back in.
=> zuul: add integration test jobs back in

.zuul.d/project.yaml
So Zuul doesn't end up merging every commit from a PR individually but
rather squash them.
=> zuul: set project merge mode to squash-merge

setup.cfg
This will allow us to prevent unexpected backwards compatibility when
4.0.0 releases and 3.1.3 had a known regression.
Fixes: https://github.com/ansible-community/ara/issues/212
=> Pin dynaconf to <4.0.0 and exclude 3.1.3

.zuul.d/jobs.yaml, .zuul.d/project.yaml, .zuul.d/secrets.yaml
Releases were previously automated through OpenDev's Zuul and this is a
first attempt at reproducing the same implementation in Ansible's Zuul.
=> zuul: add pre-release/release job for publishing to pypi

ara/api/serializers.py, ara/api/tests/tests_file.py, ara/api/tests/tests_host.py, ara/api/tests/tests_play.py, ara/api/tests/tests_records.py, ara/api/tests/tests_result.py, ara/api/tests/tests_task.py
hosts, plays, tasks, results, files and records have references to
their parent playbook in their detailed view (i.e, ``/api/v1/hosts/<id>``)
but until now it didn't include arguments.
It turns out it would be convenient to include the arguments in this
reference so we can have it readily available for providing context.
The arguments are relatively small so it should be fine to make them
available without incurring significant overhead.
Fixes: https://github.com/ansible-community/ara/issues/220
=> api: don't exclude arguments from playbook parent references

.zuul.d/project.yaml
It doesn't work the way I thought it did. It discards all commits and
their messages, leaving only the PR subject and PR number.
=> zuul: remove squash-merge mode

ara/ui/templates/base.html, ara/ui/templates/file.html, ara/ui/templates/host.html, ara/ui/templates/index.html, ara/ui/templates/partials/host_results.html, ara/ui/templates/partials/playbook_card.html, ara/ui/templates/partials/playbook_results.html, ara/ui/templates/playbook.html, ara/ui/templates/record.html, ara/ui/templates/result.html
There are block alignment errors that distract users.
By putting container-fluid class one level higher, we avoid oversights in the child blocks.
And we improve the alignment of the blocks.
=> Move container-fluid class one level higher

ara/ui/templates/partials/pagination.html
Visually to keep the rhythm in the page, the spaces must be consistent.
This PR is there to put the same space above and below the pagination.
=> Fix pagination margin

ara/ui/templates/index.html, ara/ui/templates/partials/playbook_status_icon.html, ara/ui/templates/partials/status_icon.html
Like tags we can't filter playbooks by clicking on the status icon directly.
This patch move status icon in his own file
Status icon in filters are not badges anymore. Badge looks like button and user will be confuse to see a button next a checkbox. This is a visual preference to avoid surcharging the interface:
Before 
After
Tell me if you prefer to keep the badge.
This patch also fix the size of the control on a playbook line to make it consistent:
Before
After
=> Make playbook status icon clickable

ara/ui/templates/index.html, ara/ui/templates/partials/host_facts.html, ara/ui/templates/partials/host_results.html, ara/ui/templates/partials/playbook_results.html
Before:
After:
And host summary moved to task results header:
=> UI: Tweak search forms and host summary

ara/ui/templates/partials/playbook_card.html
0c7d8424187dfa9173f5a50c95ab930f2fcb0704 fixed the header when viewing
CLI args from the playbook index but the one from the playbook card was
forgotten.
=> ui: Fix header for CLI args in playbook card

ara/plugins/callback/ara_default.py
It was found that ansible-runner suffixes play UUIDs when running in
serial so 34cff6f4-9f8e-6137-3461-000000000005 could become
34cff6f4-9f8e-6137-3461-000000000005_2 and so on.
Truncate them to 36 characters because we don't need the suffix.
=> callback: Truncate play UUIDs to 36 characters

ara/ui/templates/partials/host_facts.html
Host facts card is an accordion, so no need to fix the height of the card.
Maybe you need to think about a way to show users there is a task result card under the host facts card
=> Remove max height on host facts card

ara/ui/templates/partials/pagination.html
=> Use link in pagination instead of button

setup.cfg
tzlocal has a pre-release for 3.0 dating back to 2020 and it breaks when
installing ara with "pip install --pre ara[server]". We can revisit this
if they do end up doing an actual release.
=> setup.cfg: pin tzlocal to <3.0

ara/ui/templatetags/truncatepath.py
`len(dirname) + len(basename)` is 1 less than `len(path)`, so this could end up returning the entire path that was passed in with "..." prepended. Plus, to always return something that is both less than `count` and shorter than the input we need to account for the prepended string and handle the case where the filename on its own is very long.
Some of the things passed to this function are not actually paths but should probably still be shortened.
Before:
After:
=> ui: Fix truncatepath calculations

tests/with_container_images.yaml
See: https://github.com/ansible-community/ara/issues/286
=> zuul: elevate privileges to workaround buildah issue

ara/api/filters.py, ara/api/tests/tests_task.py
This allows to search a task by play id such as:
``/api/v1/tasks?play=<id>``
This was always meant to be possible but was apparently forgotten.
=> api: Add support for searching tasks by play

ara/plugins/callback/ara_default.py
When running a playbook with free strategy, multiple hosts could be running different playbook tasks at the same time. This caused ARA to associate results to the wrong task id, resuting in task names not matching the task result in the ARA web interface.
Now, the task is cached by it's uuid. The task result includes the task uuid, so this is used to ensure the correct task id is associate with a particular result.
=> Add caching for tasks in callback plugin

tests/basic.yaml, tests/integration/free_strategy.yaml, tests/test_tasks.yaml
This ensures that ara records tasks and results properly, even when
using the free strategy.
This is meant to go along with the PR that added the fix: https://github.com/ansible-community/ara/pull/268
=> tests: Add integration test for free strategy

ara/ui/templates/host_index.html, ara/ui/templates/index.html
The index and host_index templates relied on pagination data to provide
context in the page titles. These turned out empty when doing static
generation since there is no pagination there.
=> ui: Fix page titles when using static generation

ara/ui/templates/partials/api_link.html, ara/ui/views.py
The API link changes based on the page that is displayed to best fit a
general API call for the resource the user is looking at.
Because the new host index uses latesthosts by default, point to
/api/v1/latesthosts but if all reports are included, provide
/api/v1/hosts instead.
=> ui: toggle between API links for hosts and latesthosts

ara/ui/templates/partials/host_results.html, ara/ui/templates/partials/playbook_results.html, ara/ui/views.py
Displaying that a task had been delegated in the details of a result
didn't feel sufficient so we'll highlight it in the result tables as
well.
=> ui: highlight delegated tasks in the results table

ara/api/filters.py
When querying for created or updated dates for the latesthost endpoint,
filter on the dates of the referenced host instead.
=> api: filter latesthost dates on the nested host instead

ara/api/filters.py, ara/ui/views.py
commit 982f1a84422654ff31a5a7c1e92ea122a9054e98 made it so we could no
longer filter by created or updated for LatestHost which made it
inconsistent with all the other endpoints.
This adds host__ fields to filter on the nested host fields instead.
=> api/ui: restore filtering on latesthost & add nested date filtering

ara/plugins/callback/ara_default.py
When delegate_to is a variable and the task is skipped, Ansible doesn't
template the variable before sending it to the callback.
We can afford to work around this for skipped tasks.
=> callback: don't record delegate_to if the task was skipped

ara/plugins/callback/ara_default.py, tests/integration/delegate_to.yaml
8df13a99ba41ecac4040db11caa867e2c9c98b72 avoided recording tasks with
delegate_to that had been skipped entirely due to a 'when' condition
because Ansible doesn't template the variable sent to the callback.
It turns out that we also need to avoid recording it for skipped items
while in a loop because the delegate_to also doesn't get templated by
Ansible.
=> Don't record delegate_to for skipped loop items

ara/api/serializers.py
This PR fixes issue #311.
Through the introduction of the "deleagted_to" field in the result object, the API endpoint `//api/v1/results` expects `delegated_to` as mandatory field in the payload. Because previous ara callback version does not have this ara would not be compatible with older callback versions anymore.
The fix is simple, by only adding a `required=False` in the serializer.
=> Ensure compatibility with previous ara callback versions

MANIFEST.in
The files in these directories are not intended to ship in the release package tarballs.
=> packaging: Add a MANIFEST.in to exclude some source files

ara/ui/templates/host_index.html
It may not be obvious at first glance what this does.
Add a short tooltip to make it clearer.
=> ui: Add a tooltip over 'include all playbook reports'

ara/ui/management/commands/generate.py
Otherwise the about modal doesn't include the version of ara.
=> ui: Include ARA_VERSION when generating static reports

setup.cfg
psycopg2 2.9 included a change that works with the latest django LTS
(3.2) but breaks 2.2.
Django maintainers have acknowledged the issue and documented that
psycopg2 is supported only through 2.8.6 for Django 2.2:
https://docs.djangoproject.com/en/2.2/ref/databases/#postgresql-notes
=> setup.cfg: pin psycopg2<2.9

ara/api/renderers.py, ara/server/settings.py
If you are running ara in production you will collect a lot of data over time. This will slow down the browsable API because of the population of related keys into the dropdowns of the html POST/PUT form. 
This is noticed most strongly in the results API view (`/api/v1/results` or `/api/v1/results/X`) because there we have a lot of related fields (delegated_to, host, task, play, playbook). (compare #323)
Because the browsable API is really nice, we need a solution, where we can still browse the API, and also post data if we want, but withouth this huge performance overload.
This code change is based on a anwser on stackoverflow: https://stackoverflow.com/questions/18587726/django-rest-framework-slow-browsable-ui-because-of-large-related-table and just disables the html forms.
That's how …
=> Disable html forms in browsable api

ara/server/__main__.py, ara/setup/exceptions.py
Add a friendlier exception when attempting to run with psycopg>=2.9
because 8e6932a39987ad542202859b58213741568c38cc is not sufficient.
Related to issue https://github.com/ansible-community/ara/issues/320.
=> server: Handle exception when running psycopg2>=2.9

.zuul.d/jobs.yaml, .zuul.d/project.yaml, .zuul.d/secrets.yaml, tests/zuul_publish_container_images.yaml
We used to do this before migrating to this instance of Zuul, see
3053583ddb6e088fb59a9fa8508438a46561d257.
This adds the jobs back in such that container images will be built,
tested and published to dockerhub and quay.io every time a new PR is
merged.
=> zuul: Add a post job to build and publish container images

tests/zuul_publish_container_images.yaml
In f1de47778311c81fc0c8f7f8c72edc591c2eebb6 we added a workaround for an
issue by escalating privileges when building and testing images.
We need to escalate when publishing as well otherwise the unprivileged
user won't see the images that were built prior.
=> zuul: escalate privileges when publishing container images

tests/zuul_publish_container_images.yaml
When updating from centos8 to centos8-stream we renamed the image and
forgot to use the right name here.
=> zuul: image name is now centos8-stream-pypi-latest

tests/linters.sh
This has recently come up which is a similar test to the one we were
already ignoring.
=> tests: skip bandit B324 test, we're not using sha1 for security

ara/server/settings.py, doc/source/api-configuration.rst
Problem:
- Ansible log file contains only warning when ARA's callback plugin is set. 
- User LOGGING configuration was not used 
Context:
As mentioned in issue #228, `Django` logging variable was not defined correctly. It was missing a function call to gather user's logging configuration from `dynaconf` like so:
```python
LOGGING = settings.get("LOGGING", ...)
```
Also, due to default LOGGING configuration, when ARA's ansible callback plugin is set, and `log_path` is set in `ansible.cfg`, this result in fewer logs inside ansible log file. Mostly warnings. It happening because ansible logging system uses the `root` configuration to generate its `FileHandler` logger. cf: https://github.com/ansible/ansible/blob/6f445ca6e5c9c8b85ccc5062e00508c69ca26fde/lib/ansible/utils/display.py#L166-L178 …
=> logging: fix no logs when ARA callback set

ara/server/settings.py, ara/setup/env.py
- Dynaconf updated their args for parsing configuration (ENV, file, etc). Old arguments are now deprecated.
- `distutil.sysconfig` is deprecated and will be removed in `v3.12` [news](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated)
closes #363
closes #344
=> fix: remove deprecation warnings

ara/cli/host.py, doc/source/cli.rst
This mirrors the functionality provided by the hosts page of the
reporting interface.
By specifying --latest, only the latest playbook report will be
returned for each host.
=> cli: add --latest to 'ara host list'

setup.cfg
=> chore: change configuration keys naming convention for setup.cfg python3.10

setup.cfg
dynaconf 3.0.0 dropped support for python3.5 by introducing f-strings
which landed in python3.6 and resulted in ara not working under py35.
Let's pin it in order to do a last release compatible with py35 and it
can be removed later.
Closes: https://github.com/ansible-community/ara/issues/370
=> Pin dynaconf to <3.0.0 when using python3.5

ara/plugins/callback/ara_default.py, tests/basic.yaml, tests/integration/lookups.yaml
In use cases where playbooks are run against localhost, it might be
useful to record results under the fqdn of the host instead in order to
differentiate task results belonging to different hosts.
TODO:
- integration tests
- docs
=> Add a localhost_to_hostname toggle in the ansible callback

ara/plugins/callback/ara_default.py
When troubleshooting callback or playbook execution issues, it can be
useful and relevant to see which hook is currently being run.
=> callback: add some missing callback hook debugging

ara/ui/templates/partials/host_results.html, ara/ui/templates/partials/playbook_results.html
They don't take up too much width, let's put them there and include just
the number.
=> ui: Move task tags to their own column

tests/zuul_publish_container_images.yaml
source-latest means it is coming from the master branch which can be
disruptive, especially with larger changes coming.
Let's set latest to point to the latest pypi release which is more
stable instead.
=> container-images: tag latest from pypi-latest instead of source-latest

ara/server/__main__.py, ara/setup/exceptions.py, doc/source/api-configuration.rst, setup.cfg
We've been recommending django 2.2 LTS and now that 3.2 has been out for
almost a year, we should bump the requirement.
=> requirements: update django to 3.2 LTS

ara/ui/templates/partials/host_results.html
They should be centered and display only the number.
=> ui: Fix display of task tags when viewing host results

.zuul.d/jobs.yaml, .zuul.d/nodesets.yaml, .zuul.d/project.yaml
- Bump jobs from Fedora 35 to Fedora 36
- Bump from Ansible 5 to Ansible 6 (ansible-core 2.13 underneath)
- Remove ansible-base 2.10 (it's EOL), keep ansible 2.9 a while longer
=> zuul: Update versions of things tested in CI

ara/clients/http.py, ara/clients/utils.py, ara/plugins/callback/ara_default.py
This PR adds support for configuring a TLS client certificate and CA.
=> Add support for configuring `HttpClient` TLS client certificate and CA

.zuul.d/jobs.yaml, ara/server/settings.py, contrib/container-images/README.rst, contrib/container-images/centos-pypi.sh, contrib/container-images/centos-source.sh, contrib/container-images/fedora-distribution.sh, contrib/container-images/fedora-pypi.sh, contrib/container-images/fedora-source.sh, setup.cfg, tests/with_container_images.yaml, tests/zuul_publish_container_images.yaml
- Update from CentOS Stream 8 to Stream 9
- Update from Fedora 35 to Fedora 36
=> contrib: bump OS versions for container images

tests/with_container_images.yaml, tests/zuul_publish_container_images.yaml
To help troubleshooting when there are issues, run a 'buildah images' to
list the images that were built as part of the job.
=> contrib/zuul: List the container images that were built

contrib/container-images/centos-pypi.sh, contrib/container-images/centos-source.sh, contrib/container-images/fedora-pypi.sh, contrib/container-images/fedora-source.sh
- Fix mysql/postgresql support that was broken in recent overhaul
- Drop psycopg2-binary and go back to psycopg2, at first glance it
doesn't work in-place with django
- Keep psycopg2<2.9 requirement for pypi images but remove it from the
source images since django 3.2 fixes support for psycopg2>2.9. We
can lift the requirement for the pypi images once ara 1.6.0 is out.
- Fix 'dnf history undo' implementation to uninstall development
dependencies
- Fix missing container ID when setting the timezone for centos-pypi
=> contrib: Various container image fixes

.zuul.d/jobs.yaml
Otherwise a change only under contrib/container-images wouldn't trigger
them.
=> zuul: Tweak files in post jobs to ensure they trigger

ara/plugins/callback/ara_default.py, tests/basic.yaml, tests/integration/facts.yaml, tests/test_tasks.yaml
This will fixes #397
support for `ansible.builtin` as well as for `ansible.legacy` FQCN
=> support FQCN for setup and gather_facts

ara/cli/base.py, ara/cli/expire.py, ara/cli/host.py, ara/cli/play.py, ara/cli/playbook.py, ara/cli/record.py, ara/cli/result.py, ara/cli/task.py
When first implementing support for ssl key/cert/ca validation in the CLI, we missed that there was already a --key argument, used for ara_record keys.
Add a prefix to the ssl arguments such that --key becomes --ssl-key in order to resolve the conflict.
=> CLI: prefix ssl arguments with "ssl-"

ara/server/settings.py, ara/server/wsgi.py
@dmsimard This is a follow up to the previous PR. Let me explain the rationale for it:
* I changed `WSGI_APPLICATION` to be static and then do the switch in `wsgi.py`. This has the benefit that the docker container that runs `gunicorn ara.server.wsgi` works out of the box. Accessing settings in `wsgi.py` is okay because `get_wsgi_application()` does it as well.
* I hardcoded `ara.server.db.backends.distributed_sqlite` as ENGINE if distributed sqlite is enabled because there is no way any other database engine would be valid for it. The way I have written it also prevents `ara.server.db.backends.distributed_sqlite` from being written into settings.yml, so one can turn `DISTRIBUTED_SQLITE` on & off at will without having to change the engine in settings to match…
=> Improved WSGI app selection and hardcoded db backend when distributed sqlite is in use.

ara/clients/http.py
The purpose of this PR is to disable the requests warning when using `--insecure` or `ARA_API_INSECURE`
Fixes #356
=> Disable InsecureRequestWarning for insecure requests

ara/api/filters.py, ara/ui/forms.py, ara/ui/templates/partials/host_results.html, ara/ui/templates/partials/playbook_results.html
Ability to search for host or task name instead of id (fixes #243)
Furthermore this PR introduces host and task name filters on the playbook index as well
While the taskfilter supports pattern search (`icontains`), the host filter expects case insensitve exact expression (`iexact`). Because imo that's how most will use it.
=> ui: ability to search by host or task name

ara/server/wsgi.py
Otherwise the wsgi application wouldn't route the healthcheck endpoint properly since it doesn't contain the expected prefix.
Fixes: https://github.com/ansible-community/ara/issues/435
=> server: properly route /healthcheck/ under distributed_sqlite

.zuul.d/jobs.yaml, .zuul.d/project.yaml
- 2.14 hasn't been released yet but they have branched and it'll be out soon.
- Bump ansible to 6.4.0 while 7.0.0 is in alpha
=> zuul: add tests for 2.14 and update to 6.4.0

ara/server/wsgi.py, ara/ui/templates/base.html, ara/ui/templates/distributed_index.html, ara/ui/templatetags/strip_db.py, ara/ui/urls.py, ara/ui/utils.py, ara/ui/views.py
The index when using the distributed sqlite backend was a 404 not found which isn't very helpful.
Add a simple (but useful) index that contains a list of databases and we can improve it later.
=> ui: Add a simple index for the distributed sqlite backend

setup.py
PyPI defaults to rst and we've changed the README to markdown since 1.5.8.
For reference: https://pypi.org/help/#description-content-type
=> setup.py: Declare the readme as markdown

contrib/container-images/centos-pypi.sh, contrib/container-images/centos-source.sh, contrib/container-images/fedora-pypi.sh, contrib/container-images/fedora-source.sh, setup.cfg
Not sure if there was a reason to limit psycopg2 to < 2.9. If there is, we could limit globally in setup.cfg now as well.
=> Use package extras consistently.

ara/ui/templates/index.html
Fields that can be very long are generally truncated in tables with the full version available on mouse-over.
This is a compromise to avoid a single column taking up most of the width available in the table.
controller hostnames can be up to 255 characters so truncate them like we do elsewhere.
=> ui: truncate long controller hostnames

.zuul.d/jobs.yaml, .zuul.d/nodesets.yaml, .zuul.d/project.yaml, contrib/container-images/README.rst, contrib/container-images/centos-pypi.sh, contrib/container-images/fedora-distribution.sh, contrib/container-images/fedora-pypi.sh, contrib/container-images/fedora-source.sh, tests/container_test_tasks.yaml, tests/with_container_images.yaml, tests/zuul_publish_container_images.yaml, tox.ini
The container images and CI tests had gone a bit stale in the time I was away.
- containers: updated fedora base image from 36 to 38
- containers: updated centos-pypi image from stream8 to stream9
- zuul: Update fedora base image from 36 to 38
- zuul: Update ansible version tested from 6.4.0 to 8.1.0
- zuul: Update versions of ansible-core tested (2.9, 2.14, 2.15)
=> Update versions, integration tests and container images

README.md, setup.cfg
See: https://github.com/ansible-community/ara/issues/485
Django 4.2LTS was released in April 2023 and 3.2LTS will be supported until April 2024: https://docs.djangoproject.com/en/4.2/releases/4.2/
Django 4.2 raises the Python requirement from 3.6 up to 3.8 so in effect it means we are also raising the requirement for ara itself.
Given the change in requirements, this will warrant a version bump for ara from 1.6.1 to 1.7.0.
=> maintenance: Bump version of django from 3.2LTS to 4.2LTS

doc/source/api-configuration.rst
We've updated to django 4.2 in 4144916fd3167aabfd2daac538bef0d937f94776, we should also update the links in the documentation.
=> docs: update links to use django 4.2

ara/plugins/callback/ara_default.py
In some environments (e.g. containers), the user and hostname detected from the OS might not be relevant or useful. This change allows the user to pass in customized values for these attributes which override the automatic detection.
Note: I didn't see any tests for things like the the the controller name or user name, or any other playbook level attributes, so I didn't add any here.
Closes #493
=> Allow manually defining user & hostname in callback plugin

ara/plugins/callback/ara_default.py
ara records the task content by default which could contain secrets. This can now be made optional with a new setting:
- ARA_RECORD_TASK_CONTENT (or record_task_content in ansible.cfg)
Signed-off-by: Tom Siewert <tom@siewert.io>
=> callback: Make task content recording optional (rebased)

ara/server/settings.py
Django expects a directory with static files but we are using whitenoise to serve the files transparently. We can ignore this warning.
Fixes: https://github.com/ansible-community/ara/issues/492
=> django: ignore warning about static directory

.zuul.d/jobs.yaml, .zuul.d/project.yaml, tests/basic.yaml, tests/integration/lookups.yaml, tests/integration/record_settings.yaml, tests/test_tasks.yaml
There are three new settings which needed some amount of testing coverage:
- ARA_RECORD_USER_NAME (to manually override the recorded user for a playbook)
- ARA_RECORD_CONTROLLER_NAME (to manually override the recorded controller for a playbook)
- ARA_RECORD_TASK_CONTENT (to prevent ara from recording task content)
This improves the coverage while fixing a gap that we had about controller and user name recording.
Fixes: https://github.com/ansible-community/ara/issues/506
=> callback: add tests for ARA_RECORD_* settings

.zuul.d/jobs.yaml
It is currently the latest version.
=> zuul: bump version of ansible 8 to 8.3.0

ara/ui/templates/partials/search/tasks.html
A copy/paste error snuck by during the refactor to bootstrap 5 and the task search ended up posting to the playbook search which was wrong.
=> ui: fix wrong form url for task search

setup.cfg
ara currently works with both the 3.2 and 4.2 LTS versions of django and django 3.2 is maintained until April 2024.
We can be flexible on the version of django for now.
Fixes: https://github.com/ansible-community/ara/issues/485
=> requirements: adjust django requirement to >=3.2,<4.3

doc/requirements.txt
This django requirement is used when building documentation and should match the version of django we have in the project's main requirements.
=> docs: bump version of django in docs/requirements.txt

ara/ui/templates/partials/api_link.html
It's intended that the API link changes based on the page.
The playbook list and host list links were fine but it seems we had forgotten about the task list link.
=> ui: Fix link to the API when browsing tasks

contrib/container-images/centos-pypi.sh, contrib/container-images/centos-source.sh, contrib/container-images/fedora-pypi.sh, contrib/container-images/fedora-source.sh
To avoid import problems such as in https://github.com/ansible-community/ara/issues/406#issue-1330390967 or #514 it is more safe to call `gunicorn` via `python3 -m` same as it is done with `pip`
=> python3 -m gunicorn instead of /usr/local/bin/gunicorn as container entry command

.zuul.d/jobs.yaml, .zuul.d/nodesets.yaml, .zuul.d/project.yaml, ara/api/tests/tests_utils.py, ara/server/settings.py, contrib/container-images/README.rst, contrib/container-images/fedora-distribution.sh, contrib/container-images/fedora-pypi.sh, contrib/container-images/fedora-source.sh, tests/with_container_images.yaml, tests/zuul_publish_container_images.yaml
ruamel.yaml>=0.18 deprecated the use of .dump which we historically used that maintained compatibility between pyyaml and ruamel.yaml.
We can eventually remove this pin when we change our usage of dump.
https://github.com/ansible-community/ara/issues/524
=> settings: fix deprecated use of .dump in ruamel.yaml

ara/ui/templatetags/diff_result.py
This fixes diffs in task results that only have "prepared" key in them from looking like this:
To being properly formatted and colorized, like diffs with "before" and "after" keys in them look.
Ansible produces diffs with "prepared" key instead of before/after in plugins like git, apt, cli_config already.
But also some network devices (e.g. Arista EOS, Cisco IOS, etc) can only produce diffs like this between normalized candidate and running configurations, where it is tricky or impossible to do local diff, without on-device knowledge about configuration format normalization.
(I've bumped into this issue with arista.eos ansible collection in particular)
Thanks.
=> ui: fix displaying result diffs with "prepared" key

ara/ui/templates/partials/tables/playbook_results.html
It used to be that sort_by_date and sort_by_duration accepted a "form_url" argument before 1.7.0 but it is no longer the case.
Like the playbook list, use an in-line form element instead.
Fixes: https://github.com/ansible-community/ara/issues/543
=> ui: Fix sorting playbook results by date and duration

ara/api/management/commands/prune.py, ara/cli/host.py, ara/cli/playbook.py, ara/cli/record.py, ara/cli/result.py, ara/plugins/callback/ara_default.py, ara/server/wsgi.py
As linked on https://github.com/ansible-community/ara/issues/546, Python 3.13 finally removed the deprecate `.warn()`, so we now need to use `.warning()` instead.
=> support logging on Python 3.13 fixed #546

setup.cfg
It should generally be picked up by the dynaconf yaml extras but it was found to not always be the case (i.e: Fedora koji) so make it explicit since there is no harm in doing so.
=> setup.cfg: make ruamel.yaml dependency explicit

doc/source/index.rst, doc/source/introduction.rst
Copied from the FAQ, "Why ARA and not <X>"
(It's nice to have the docs begin by explaining what the software does.  :)
=> Docs: Add introduction, say what ARA does

.readthedocs.yaml
For some time now readthedocs has changed how they build docs and now require a .readthedocs.yaml configuration file as explained in https://docs.readthedocs.io/en/stable/config-file/index.html
Let's add the file to fix the documentation builds.
=> docs: add .readthedocs.yaml configuration

.readthedocs.yaml
It turns out that there is no image for 24.04 yet.
=> docs: make readthedocs use ubuntu 22.04

doc/changelog-release-notes.sh, doc/source/changelog-release-notes.rst, doc/source/conf.py, doc/source/contributing.rst, doc/source/faq.rst, doc/source/getting-started.rst, doc/source/troubleshooting.rst
The getting started guide was originally a copy from the README
and it accidently became stale and out of date as the README was
improved and maintained.
We can make the README even better eventually and there shouldn't
be two sources of truth.
Let's keep the README for this and link to it instead.
ara-web has been archived in February 2023, update the docs to remove
it and add ara-collection which was missing.
Take the opportunity to refresh the question about different components
of ara running on different servers.
=> Docs refresh

.zuul.d/jobs.yaml, .zuul.d/project.yaml, tests/integration/ignored_files.yaml
We're up to Ansible 10 and ansible-core 2.17.
=> zuul: Update versions of ansible and ansible-core tested

ara/plugins/callback/ara_default.py
Originally: https://github.com/ansible-community/ara/pull/559 (thanks @Nudin)
> This will catch SIGINT/SIGTERM and send an update to the ara server, so
that the playbook does not continue to be shown as running indefinitely
but will report failed. See https://github.com/ansible-community/ara/issues/556
> After sending the update to the server, it executes any handler that where
configured so far in order not to interfere with other parts of
ansible/ansible plugins or if none was present, exit with the appropriate exit code.
This is a great improvement over eventually expiring playbooks that were interrupted with the CLI: https://github.com/ansible-community/ara/blob/master/ara/cli/expire.py
I am sure some interruptions will not be salvageable depending on how bad things were interrupted …
=> Catch SIGINT and SIGTERM, record interrupted playbooks as 'expired'

ara/clients/utils.py
It looks like requests supports utf-8, but only if it is pre-encoded by the caller. Otherwise, it tries to encode both parameters using latin-1.
See 
https://github.com/psf/requests/blob/a3ce6f007597f14029e6b6f54676c34196aa050e/src/requests/auth.py#L56-L60 https://github.com/psf/requests/issues/3662
https://github.com/pallets/werkzeug/issues/945
=> client: allow using utf-8 usernames and passwords

contrib/container-images/README.rst, contrib/container-images/fedora-distribution.sh, contrib/container-images/fedora-pypi.sh, contrib/container-images/fedora-source.sh, tests/with_container_images.yaml, tests/zuul_publish_container_images.yaml
39 is starting to be old with 41 just recently released.
We will eventually update to 41, let's just bump a single release for now.
=> container-images: bump fedora images to fedora:40

setup.cfg
Starting with Django 4, Django will use either pytz or tzdata for timezone information via ZoneInfo.  However the ZoneInfo defaults to using tzdata. Typically this comes from the OS distribution but that isn't guaranteed. With that in mind let's install it alongside ara.
This will prevent tracebacks like:
---
Using /etc/ansible/ansible.cfg as config file
Operations to perform:
Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
No migrations to apply.
Traceback (most recent call last):
File "/usr/lib/python3.10/zoneinfo/_common.py", line 12, in load_tzdata
return importlib.resources.open_binary(package_name, resource_name)
File "/usr/lib/python3.10/importlib/resources.py", line 43, in open_binary
package = _common.get_package(package)
File …
=> Install tzdata when installing ara[server]

ara/plugins/callback/ara_default.py
The Ansible-facts `gather_subset` allows for the value `all` to be supplied: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html#parameter-gather_subset
It would be logical that ARA allows users to ignore all facts the same way.
This PR adds that functionality.
This is especially useful as some facts are dynamically named - like network-interface facts.
=> Client: Enable to ignore all facts

tests/with_container_images.yaml, tests/zuul_publish_container_images.yaml
In 18669af186b3e60cc8780e62b7fdc9f231b60ae8 we updated the base image of the container images but we didn't actually publish them under the new fedora41 tags because we forgot to update these.
=> containers: publish new fedora41 tags

ara/plugins/action/ara_label.py, doc/source/ansible-plugins-and-use-cases.rst, tests/integration/roles/smoke-tests/tasks/ara-ops.yaml
This action plugin gives the ability to manipulate playbook labels in ara from within ansible playbooks.
It includes docs and integration tests.
See issue: https://github.com/ansible-community/ara/issues/596
=> Add a new ara_label Ansible action plugin
