ansible-community/ara

ara/ui/templates/index.html, ara/ui/templates/partials/playbook_results.html
You use a h5 inside a button and this is probably not good in term of accessibility.
An other problem is that h5 introduce a little bottom margin, so the text is not align vertically.
If you want to make the text bigger in a button, you can use the btn-lg class modifier.
This modifier fix the problem of the bottom margin also.
=> Fix vertical alignment of the search button

ara/ui/static/css/ara.css, ara/ui/templates/index.html, ara/ui/templates/partials/playbook_card.html
=> ui: try a different color scheme for labels

ara/server/context_processors.py, ara/server/settings.py, ara/ui/templates/base.html, ara/ui/templates/partials/about_modal.html
Updated version of a PR raised by Guillaume: https://github.com/ansible-community/ara/pull/254
Co-Authored-By: Guillaume Vincent <gvincent@redhat.com>
Co-Authored-By: David Moreau-Simard <moi@dmsimard.com>
=> ui: Add about modal with links and version information

doc/source/index.rst, doc/source/troubleshooting.rst
Some issues are frequent enough to warrant documenting so we can
refer users to them.
=> docs: First iteration of troubleshooting docs

README.rst, doc/requirements.txt
See: https://github.com/ansible-community/ara/issues/275
=> readme: update irc from freenode to libera.chat

ara/ui/forms.py, ara/ui/management/commands/generate.py, ara/ui/templates/base.html, ara/ui/templates/host_index.html, ara/ui/templates/index.html, ara/ui/templates/partials/api_link.html, ara/ui/templates/partials/host_facts_snippets.html, ara/ui/templates/partials/host_index_row.html, ara/ui/templates/partials/host_results.html, ara/ui/templates/partials/playbook_results.html, ara/ui/templates/partials/sort_by_date.html, ara/ui/templates/partials/sort_by_name.html, ara/ui/templatetags/datetime_formatting.py, ara/ui/urls.py, ara/ui/views.py
Change-Id: Ib72729c2ead01a48ae8639007161b98c99a80a2
This is a work in progress that adds a host index a bit like the playbook index so you can browse, search and query for hosts instead of playbooks.
=> ui: First iteration of the new host index

ara/ui/views.py
The intent was to order hosts by their latest update with the most
recent at the top: -updated.
However, it turns out that we were sorting LatestHost objects instead of
Host objects. This commits fixes it so we sort based on the date of the
host, not the latesthost reference.
=> ui: Fix latest host report ordering by date

ara/ui/templates/host_index.html, ara/ui/templates/index.html
We have a similar message elsewhere when no results are found, let's add
one here too.
=> ui: Add a message when no playbooks are found

ara/api/tests/tests_latesthost.py, ara/api/views.py
We have a custom perform_destroy that runs when deleting a host via the
API (DELETE /api/v1/hosts/<id>) that takes care of updating the
latesthost entry.
However, because hosts get deleted via the database model
(on_delete=models.CASCADE) when deleting a playbook via the API, the
latesthost entry would get deleted when the host was deleted instead of
being updated.
This adds a very similar perform_destroy for playbooks that iterates
over the hosts and if one of the hosts happens to be a LatestHost, it
will update the entry before deleting.
=> api: Update LatestHost when deleting a playbook

.zuul.d/nodesets.yaml, .zuul.d/secrets.yaml
We're migrating CI to another instance of Zuul which has slightly
different nodesets and we need to re-encrypt the secrets.
=> zuul: Update config to work with software factory

ara/api/tests/tests_utils.py
=> Some tests misusing assertTrue for comparisons fix

.zuul.d/jobs.yaml, tests/basic.yaml, tests/zuul_docs.yaml
This lets us test what is currently the latest release.
=> zuul: Bump ansible version to 5.5.0 and other CI fixes

.zuul.d/jobs.yaml, .zuul.d/project.yaml
2.13 has been released, we should test it too.
=> zuul: Add a job to test ansible-core 2.13

README.md, doc/source/troubleshooting.rst
- Some grammar and phrasing
- Some clarifications
- Copied paragraph from documentation about security and production use
- Provide more context about what the server is and how to run it
- Add advice about performance when using a server
=> readme and performance: updates and cleanup

ara/cli/base.py, ara/cli/expire.py, ara/cli/host.py, ara/cli/play.py, ara/cli/playbook.py, ara/cli/record.py, ara/cli/result.py, ara/cli/task.py
We recently added support for a custom CA and client cert in the
callback, this adds it to the CLI as well.
=> CLI: Add support for CA and client cert

ara/api/filters.py, ara/ui/forms.py, ara/ui/templates/host_index.html, ara/ui/templates/partials/host_index_row.html
Improvements on host index site. Background: #331 
* filter possibility for playbook name and path
* playbook name column in table
=> Host index improvements

ara/ui/templates/host_index.html, ara/ui/templates/index.html, ara/ui/templates/partials/playbook_results.html, ara/ui/templates/task_index.html
=> Pretty aligned search boxes

ara/ui/templates/index.html
* link on user column to quickly filter on it
* added title for this column
* also added missing title for ansible version and controller
* left aligned user column
(fixes #431)
=> filter link on user field

ara/cli/base.py, ara/clients/utils.py
These will result in cleaner exceptions should there be anything wrong.
Fixes https://github.com/ansible-community/ara/issues/402
=> client: Validate access of SSL files before using them

ara/ui/static/css/ara.css, ara/ui/templates/host.html, ara/ui/templates/host_index.html, ara/ui/templates/index.html, ara/ui/templates/partials/host_facts.html, ara/ui/templates/partials/host_index_row.html, ara/ui/templates/partials/host_results.html, ara/ui/templates/partials/playbook_card.html, ara/ui/templates/partials/playbook_hosts.html, ara/ui/templates/partials/playbook_results.html, ara/ui/templates/partials/task_index_row.html, ara/ui/templates/task_index.html
This pushes information that are less relevant further away to the right such that the more relevant things are closer to the left.
=> ui: re-order table columns and improve consistency

ara/ui/templates/host.html, ara/ui/templates/index.html
I'll keep this PR opened for a while, we can put the fixes we find for rc1 here.
- ui: center the user cell in the playbook list table
=> 1.6.0rc1 fixes

ara/plugins/callback/ara_default.py
=> fix callback plugin creates broken folder in the current working directory #469

README.md
And kind of keep the Twitter link because there's a lot of content there.
=> readme: Add link to mastodon

ara/ui/templatetags/pygments_highlights.py
The detection of diff content is a bit basic, but seems to work good enough for now.
PS: Thanks for your talks in Gent.
=> Highlight diff output

ara/api/models.py, ara/plugins/callback/ara_default.py, doc/source/api-configuration.rst, doc/source/cli.rst
=> Fix some typos

ara/ui/static/css/ara.css, ara/ui/static/js/auto-refresh.js, ara/ui/templates/base.html
An arrow drop-down menu at the top right that
auto refreshes ara (another recursive acronym).
- Disabled by default
- Duration selection saved across loads in local storage
- 3 seconds before a refresh, the arrow turns green and spins
=> ui: Add an auto-refresh feature

ara/plugins/callback/ara_default.py, doc/source/ansible-plugins-and-use-cases.rst, doc/source/conf.py, tests/basic.yaml, tests/integration/facts.yaml, tests/integration/ignored_facts.yaml, tests/test_tasks.yaml
Following the addition of supporting "all" as the value of ignored_facts, we should take the opportunity to document the feature and then test that it works.
=> ignored_facts: Add a bit of docs and tests
